modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (28 is current forge version)
issueTrackerURL="http://github.com/oitsjustjose/persistent-bits/issues"
[[mods]]
modId="persistentbits"
version="${version}"
displayName="Persistent Bits"
displayURL="http://github.com/oitsjustjose/persistent-bits"
credits="LexManos for help with the new chunkloading mechanics via https://github.com/LexManos/ChunkNoGoByeBye \nhttps://reddit.com/u/fuami-cake for the model"
authors="oitsjustjose"
description='''
A super simple chunk-loading mod which works across world loads - uses the vanilla /forceload mechanic!
'''
[[dependencies.persistentbits]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.persistentbits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
